### ISSUE TITLE
fatal error: 'tr1/functional' file not found

### ISSUE THREAD

**Issue by ryandesign** [pfi/pficommon#166]
pficommon does not build on OS X 10.9 or later, because it uses the transitional "tr1" namespace which is no longer available in OS X 10.9 or later:

```
pficommon-26b6655092adc95649c39706b37502e466e5efe9/src/concurrent/../lang/function.h:35:10: fatal error: 'tr1/functional' file not found
#include <tr1/functional>
         ^
1 error generated.
```

Note: if you want to retain compatibility with OS X 10.8 or earlier, you have to continue using "tr1" on those systems. So you'll have to detect whether "tr1" exists or not and act accordingly.

**Comment by gwtnb** [comment]
Thank you for reporting. We made pficommon for OS X 10.9+ https://github.com/gwtnb/homebrew-pficommon/ but porting some functions to OS X 10.9+ takes time. We are using pficommon primarily for GNU/Linux, so we will port to OS X 10.9+ if we have to do so.

**Comment by ryandesign** [comment]
I'm writing on behalf of the MacPorts project, where we currently have pficommon 83ea9e102fbe9dfd788f49b69f18585355f64692 from 20141020. It only builds on OS X 10.7 and 10.8, but not on earlier or later versions of OS X; this is somewhat limiting.

It looks like in the Homebrew formula you referred me to, an earlier version of pficommon from 20140813 is being used. I suppose we can downgrade pficommon in MacPorts to an older version if that will bring compatibility with a wider range of OS X versions, but it would be good to get the current version working on more OS X versions. The problem I mentioned above, about the tr1 namespace, isn't exactly an OS X-specific issue; I imagine you would see the same problem on any other system that has moved from the transitional implementation to the final implementation.

**Comment by ryandesign** [comment]
Your latest code still does not build with libc++.

You don't need a Mac to reproduce this issue, since [libc++ is available for many systems](https://libcxx.llvm.org/docs/UsingLibcxx.html).
